#!/bin/sh
export PATH=$PATH:/usr/bin:/usr/local/bin

/root/.apps/openbsd-bwusage/update-bandwidth-stats && \
  /root/.apps/openbsd-bwusage/bwusage | \
  mail -s "Bandwidth usage on `hostname` for `date +%Y.%m.%d`" \
  user@example.org
